name: Docker Multi-Platform CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Date Tag
        id: date_tag
        run: |
          DATE_TAG=$(date -u +%Y%m%d)
          echo "DATE_TAG=${DATE_TAG}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            dhr2333/beancount-trans-assets:${{ steps.date_tag.outputs.DATE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max