name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          ecr: false

      - name: Build amd Push
        run: |
          DATE_TAG=$(date +%Y%m%d)
          docker build . --file Dockerfile --tag dhr2333/beancount-trans-assets:$DATE_TAG
          docker push dhr2333/beancount-trans-assets:$DATE_TAG
